./build_demo_1_applaudio.sh
./build_demo_2_applaudio.sh
./build_demo_3_applaudio.sh
./build_demo_4_applaudio.sh
./build_demo_5_applaudio.sh
./build_demo_6_applaudio.sh
./build_demo_7_applaudio.sh
./build_demo_8_applaudio.sh
./build_demo_9_applaudio.sh
./build_demo_10_applaudio.sh
