name: build check windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
  
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd $env:GITHUB_WORKSPACE\..
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git
          git clone https://github.com/razterizer/AudioLibSwitcher_OpenAL.git --recurse-submodules

      # Step 3: Create 3rdparty directories in D:\a\DungGine
      - name: Create 3rdparty directories
        run: |
          New-Item -ItemType Directory -Force -Path $env:GITHUB_WORKSPACE\..\3rdparty\include\OpenAL_Soft
          New-Item -ItemType Directory -Force -Path $env:GITHUB_WORKSPACE\..\3rdparty\lib

      # Step 4: Download OpenAL Soft to D:\a\DungGine
      - name: Download OpenAL Soft
        run: curl -L https://www.openal-soft.org/openal-binaries/openal-soft-1.23.1-bin.zip -o $env:GITHUB_WORKSPACE\..\openal-soft.zip

      # Step 5: Unzip OpenAL Soft to D:\a\DungGine
      - name: Unzip OpenAL Soft
        run: |
          Expand-Archive -Path $env:GITHUB_WORKSPACE\..\openal-soft.zip -DestinationPath $env:GITHUB_WORKSPACE\..


      # Step 6: List contents of source directories to verify files
      - name: List contents of OpenAL Soft directories
        run: |
          Get-ChildItem -Recurse $env:GITHUB_WORKSPACE\..\openal-soft-1.23.1-bin\include
          Get-ChildItem -Recurse $env:GITHUB_WORKSPACE\..\openal-soft-1.23.1-bin\libs
          
      # Step 6: Copy OpenAL Soft files to 3rdparty directories
      - name: Copy OpenAL Soft files
        run: |
          # Copy OpenAL Soft headers
          Copy-Item -Path $env:GITHUB_WORKSPACE\..\openal-soft-1.23.1-bin\include\AL\* -Destination $env:GITHUB_WORKSPACE\..\3rdparty\include\OpenAL_Soft\ -Force
          # Copy OpenAL32.lib (assuming it's in the libs folder)
          Copy-Item -Path $env:GITHUB_WORKSPACE\..\openal-soft-1.23.1-bin\libs\Win32\OpenAL32.lib -Destination $env:GITHUB_WORKSPACE\..\3rdparty\lib\ -Force

      # Step 7: Fix step for libsndfile (if needed)

      # Step 8: Change to the correct directory and build
      - name: Run build.bat
        continue-on-error: false  # Ensure errors are not bypassed
        run: |
          cd demos
          pwd
          dir
          .\build_demo_1.bat
