name: build windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-demos:
    runs-on: windows-latest
  
    steps:
      # Step 1: Checkout the repository.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Move to the parent directory and fetch dependencies.
      - name: Fetch dependencies
        run: |
          cd $env:GITHUB_WORKSPACE\..
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/Termin8or.git
          git clone https://github.com/razterizer/AudioLibSwitcher_OpenAL.git --recurse-submodules
          git clone https://github.com/razterizer/TrainOfThought.git
          git clone https://github.com/razterizer/3rdparty_OpenAL,git
          git clone https://github.com/razterizer/3rdparty_libsndfile.git

      # Step 12: List contents of 3rdparty includes.
      - name: List 3rdparty/include files
      #  run: ls $env:GITHUB_WORKSPACE\..\3rpdarty\include\OpenAL_Soft
        run: |
          ls $env:GITHUB_WORKSPACE
          ls $env:GITHUB_WORKSPACE/..
          ls $env:GITHUB_WORKSPACE/../3rdparty/include
          ls $env:GITHUB_WORKSPACE/../3rdparty/include/OpenAL_Soft
          ls $env:GITHUB_WORKSPACE/../3rdparty/lib

      # Step 13: Change to the correct directory and build
      - name: Run build.bat
        continue-on-error: false  # Ensure errors are not bypassed
        run: |
          cd demos
          pwd
          dir
          .\build_all_demos.bat

  build-demos-with-locked-dependencies:
    runs-on: windows-latest
    if: false
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Step 2: Move to the parent directory and fetch dependencies
      - name: Fetch dependencies
        run: |
          cd ..
          .\8Beat\fetch-dependencies.py .\8Beat\dependencies -y
      
      # Step 3: Change to the correct directory and build
      - name: Build
        continue-on-error: false  # Ensure errors are not bypassed
        run: |
          cd demos
          .\build_all_demos.bat
