name: build check windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch dependencies
        run: |
          cd ..
          git clone https://github.com/razterizer/Core.git
          git clone https://github.com/razterizer/AudioLibSwitcher_OpenAL.git --recurse-submodules

      - name: Create 3rdparty directories
        run: |
          mkdir -p ${{ github.workspace }}/../3rdparty/include/OpenAL_Soft
          mkdir -p ${{ github.workspace }}/../3rdparty/lib

      - name: Download OpenAL Soft
        run: curl -L https://www.openal-soft.org/openal-binaries/openal-soft-1.23.1-bin.zip -o ${{ github.workspace }}/../openal-soft.zip

      - name: Unzip OpenAL Soft
        run: Expand-Archive -Path ${{ github.workspace }}/../openal-soft.zip -DestinationPath ${{ github.workspace }}/../openal-soft

      - name: Copy OpenAL Soft files
        run: |
          Copy-Item -Path $env:GITHUB_WORKSPACE\..\openal-soft-1.23.1-bin\include\AL\* -Destination $env:GITHUB_WORKSPACE\..\3rdparty\include\OpenAL_Soft\ -Force
          Copy-Item -Path $env:GITHUB_WORKSPACE\..\openal-soft-1.23.1-bin\bin\Win64\OpenAL32.dll -Destination $env:GITHUB_WORKSPACE\..\3rdparty\lib\ -Force
          Copy-Item -Path $env:GITHUB_WORKSPACE\..\openal-soft-1.23.1-bin\lib\Win64\OpenAL32.lib -Destination $env:GITHUB_WORKSPACE\..\3rdparty\lib\ -Force

      - name: Build demo
        run: |
          cd demos
          .\build_demo_1.bat
